# Generated by Django 4.2.11 on 2024-03-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='salom',
        ),
    ]
